//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprav
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    
    public partial class TelephonesEntities : DbContext
    {
        private static TelephonesEntities _context;
        public TelephonesEntities()
            : base("name=TelephonesEntities")
        {
        }
    public static TelephonesEntities GetContext()
        {
            if (_context == null)
                _context = new TelephonesEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Абоненты> Абоненты { get; set; }
        public virtual DbSet<Города_и_населенные_пункты> Города_и_населенные_пункты { get; set; }
        public virtual DbSet<Служебные_телефоны> Служебные_телефоны { get; set; }
    }
}
