//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprav
{
    using System;
    using System.Collections.Generic;
    
    public partial class Абоненты
    {
        public int ID { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Адрес { get; set; }
        public Nullable<int> Номер_телефона { get; set; }
        public string Тип_абонента { get; set; }
        public Nullable<int> Город_или_населенный_пункт_ID { get; set; }
    
        public virtual Города_и_населенные_пункты Города_и_населенные_пункты { get; set; }
    }
}
