//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprav
{
    using System;
    using System.Collections.Generic;
    
    public partial class Города_и_населенные_пункты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Города_и_населенные_пункты()
        {
            this.Абоненты = new HashSet<Абоненты>();
            this.Служебные_телефоны = new HashSet<Служебные_телефоны>();
        }
    
        public int ID { get; set; }
        public string Название_населенного_пункта { get; set; }
        public string Тип_населенного_пункта { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Абоненты> Абоненты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Служебные_телефоны> Служебные_телефоны { get; set; }
    }
}
